project:
  type: website
  output-dir: docs
  render:
  - "s-*.qmd"
  - "index.qmd"

website:
  title: "Scraping examples"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - auto: "s-*.qmd"
  repo-url: https://github.com/utdata/r-scraping-examples
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

df-print: paged


