project:
  type: website
  output-dir: docs

website:
  title: "Scraping examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - paginated-tables.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

df-print: paged


