project:
  type: website
  output-dir: docs

website:
  title: "Scraping examples"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - s-bbref-batting.qmd
      - s-paginated-tables.qmd
      - s-playbill-grosses.qmd
      - s-sref-cfb-heisman.qmd
      - s-tdcj-deathrow.qmd
      - s-ut-soccer-stats.qmd
  repo-url: https://github.com/utdata/r-scraping-examples
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

df-print: paged


