---
title: "Scraping examples in R"
author: "Christian McDonald"
date: now
---

## About the site

Scraping is challenging because every example is different. As I do different scraping projects, I'll try to save examples in this repo.

## The list so far

In the navigation of this site you'll find different scraping examples, some explained mo betta than others. There may be other less-cooked examples in the repo that are not listed because they are too rare to share.

## Resources

- The [rvest](https://rvest.tidyverse.org/index.html) package documentation.
- A 30ish minute [video about the basics](https://www.youtube.com/watch?v=vU57vSbS-PY) by Albert Rapp. (I haven't watched this, but Albert generally has good tutorials.)
- Hadley Wickham's [web scraping tutorial](https://github.com/hadley/web-scraping). He presented this as a half-day session at NICAR24.
- My [Billboard Data](https://github.com/utdata/rwd-billboard-data) repo uses Github Actions and rvest to scrape on a schedule.

## To do

Too many to list, but I do want to learn [polite](https://dmi3kno.github.io/polite/) and build in some wait time.

